CREATE TABLE STUDENT (
SID SMALLINT PRIMARY KEY,
NAME varchar(10),
MAJOR VARCHAR(5),
GRADELVL CHAR(2),
AGE SMALLINT);
GO

CREATE TABLE INSTRUCTOR (
TID SMALLINT PRIMARY KEY,
NAME VARCHAR(10)
);
GO

CREATE TABLE CLASS (
NAME VARCHAR(8) PRIMARY KEY,
CLSTIME VARCHAR(5),
TID SMALLINT FOREIGN KEY REFERENCES INSTRUCTOR(TID),
ROOM VARCHAR(5))
GO



CREATE TABLE ENROLL (
STUNUM SMALLINT PRIMARY KEY FOREIGN KEY REFERENCES STUDENT(SID),
CLASSNAME VARCHAR(8) primary key FOREIGN KEY REFERENCES CLASS(NAME),
POSNUM SMALLINT);
GO
